### ISSUE TITLE
Link to GitHub on the Site

### ISSUE THREAD

**Issue by vkoves** [IndigoBox/is-it-fresh#2]
Is it Fresh is open source, and we should make sure people know if they are developers.

**Comment by rjaltman** [comment]
This has been completed. However, before I go to close this issue, there seems to be alignment issues that were pointed out in internal discussions: 

![image](https://user-images.githubusercontent.com/3650044/31003318-adf4aa7a-a4b4-11e7-9022-09f834e2ca46.png)

Should those be fixed, though, I think we can successfully close this issue now.

**Comment by vkoves** [comment]
I'm closing this issue because it's stale and the original problem was solved. If the styling problem is still important that should be a new issue.
