### ISSUE TITLE
Alteration of Header and footer

### ISSUE THREAD

**Issue by ghost** [IndigoBox/is-it-fresh#6]
The header and footer should switch information, given that forking isitfresh on GitHub is not as important as brand recognition for IndigoBox Studios. See below.

![switch mockup](https://user-images.githubusercontent.com/30378825/40754650-f39ea26a-643f-11e8-8f84-5b5f4852474f.jpg)

**Comment by vkoves** [comment]
Here's an updated mockup we agreed on:

![switch mockup](https://user-images.githubusercontent.com/3187531/41511896-7cc148e6-7245-11e8-8510-acbd256896d5.jpg)
